import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const supabaseClient = useSupabaseClient();
  const user = useUser();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>T3 Supabase</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            T3 <span className="text-[hsl(280,100%,70%)]">Supabase</span>
          </h1>

          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>

          {user ? (
            <div className="text-white">
              <div className="flex gap-4">
                <button
                  className="btn-outline btn-error btn"
                  onClick={() => supabaseClient.auth.signOut()}
                >
                  Sign out
                </button>
                <button
                  className="btn-primary btn"
                  onClick={() => router.push("/home")}
                >
                  Manage Home
                </button>
              </div>
              <div className="mt-4">
                Logged as:{" "}
                <a className="link" href={`mailto:${user.email}`}>
                  {user.email}
                </a>
              </div>
            </div>
          ) : (
            <div>
              <button
                className="btn-primary btn"
                onClick={() => router.push("/login")}
              >
                Login
              </button>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
